Loading file improv
gabrieljardim/LogFilter pull request #2
Opened 2018-12-05 05:05 UTC by GuiMartins

- Improved file loading: now only loads what has changed the file and not it all;
- Improvs: organize some things (method names and call locations);
- Fix little bug (by not selecting any file in 'Open file ...' ).

2018-12-05 05:10 UTC, GuiMartins commented on mainwindow.h
> +  unsigned int m_lastLineLoaded;
Pensei nesse cara guardar a última linha carregada para sempre carregando a partir dela.

Pensando em um arquivo de log muito grande, o unsigned int ficaria de boa? Alguma sugestão?

2018-12-05 22:42 UTC, ClaudioMota approved these changes

2018-12-06 03:43 UTC, gabrieljardim commented on mainwindow.cpp
> +  m_ui->logListView->setEditTriggers(QAbstractItemView::NoEditTriggers);
Essa parte não entendi o que faz mas confio que tu deixou mais bonito...hehe

2018-12-06 03:45 UTC, gabrieljardim commented on mainwindow.cpp
> +    m_model->appendRow(new QStandardItem(fileLines.at(static_cast<signed>(i))));
Não entendi esse signed no static_cast

2018-12-06 04:03 UTC, gabrieljardim commented on mainwindow.cpp
> +void MainWindow::onFileChanged(QString filePath) {
Essa lógica nova introduziu um bug que caso o arquivo seja apendado em cima a parada se caga toda.

Da ruim também no caso que:
Havia uma 1 linha
Ela é apagada e substiuida por outras 2
Programa vai exibir uma velha e uma nova

2018-12-06 04:06 UTC, gabrieljardim requested changes
Ve os comments ae! :-)

2018-12-14 21:31 UTC, GuiMartins commented on mainwindow.cpp
> +  m_ui->logListView->setEditTriggers(QAbstractItemView::NoEditTriggers);
Eh so pra nao deixar editar a linha da view

2018-12-14 21:32 UTC, GuiMartins commented on mainwindow.cpp
> +    m_model->appendRow(new QStandardItem(fileLines.at(static_cast<signed>(i))));
Foi removido.

2018-12-14 21:32 UTC, GuiMartins commented on mainwindow.cpp
> +void MainWindow::onFileChanged(QString filePath) {
Estou corrigindo, quando estiver pronto aviso-te.

2019-04-04 16:39 UTC, GuiMartins commented on mainwindow.cpp
> +void MainWindow::onFileChanged(QString filePath) {
Subi a correção.

2019-04-04 16:40 UTC, GuiMartins commented
@gabrieljardim tardo mas nao falho. Relembra ai o request change e avalie a correção.

2019-04-06 16:28 UTC, gabrieljardim approved these changes

2019-04-06 16:28 UTC, merged